-- No-op, kept so the migration history stays linear.
--
-- This migration originally ALTERed "EmotionSnapshot" to change two column types,
-- but the CREATE for that table lives in the LATER migration
-- 20260203113000_add_emotion_snapshot. On an empty database it therefore failed
-- ("no such table: EmotionSnapshot") and blocked every migration after it, which
-- is why `prisma migrate deploy` could not build a fresh database.
--
-- The column types it wanted are exactly what 20260203113000 creates, so dropping
-- the statements here loses nothing and makes the chain replayable.
SELECT 1;
